### ISSUE TITLE
example in jsdoc for increaseDensity is wrong

### ISSUE THREAD

**Issue by renickbell** [renickbell/konduktiva#1]
The example is this:

console.log(increaseDensity(0, 10, [0, 1, 2, 3, 5])) //[ 0, 1, 2, 3, 50, -45 ]

The problem is that the minVal should never be 0, and the ratio should always be greater than 0 and less than 1. Probably the function should check for this and return an error if the values are outside these specifications. The input array also should not contain 0s, only positive floating point numbers.

The example should be fixed as well. This would be better.

increaseDensity(0.25, 0.5, [1, 1, 2, 3, 5])

**Comment by mrname5** [comment]
Added example to jsdoc
